### ISSUE TITLE
Failing to cross-compile builds for Windows

### ISSUE THREAD

**Issue by PAI5REECHO** [JonSnowbd/ZT#11]
Trying to cross-compile a minimal application for Windows with a `build.zig` like this:
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("asd", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.install();

    @import("lib/zt/build.zig").link(b, exe, target);

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    const exe_tests = b.addTest("src/main.zig");
    exe_tests.setTarget(target);
    exe_tests.setBuildMode(mode);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&exe_tests.step);
}
```
results in:
```
zig build -Dtarget=x86_64-windows
...
error(compilation): clang failed with stderr: In file included from /tmp/asd/lib/zt/src/dep/glfw/src/win32_time.c:30:
In file included from /tmp/asd/lib/zt/src/dep/glfw/src/internal.h:186:
/tmp/asd/lib/zt/src/dep/glfw/src/win32_platform.h:68:10: fatal error: 'windows.h' file not found
```

**Comment by JonSnowbd** [comment]
Due to how ZT compiles and links libraries, cross compilation is not currently supported, but it is something I might revisit some day to include the binaries for each platform so that this is avoided. For now compiling is stuck to the current OS.

Might also be worth looking into Mach and how it managed to get GLFW cross compiling.

**Comment by PAI5REECHO** [comment]
Is GLFW the only library that's preventing cross-compilation? This is important to me so I'd be willing to work on getting ZT to use `mach-glfw` if that's the case.

**Comment by JonSnowbd** [comment]
Hey sorry for the late response, for some reason github stopped sending me emails to notify me about my repo messages.

There are other pieces that would need to be cross compile resilient, namely ImGui and STB, though the latter is probably inconsequential. I'm working to update ZT to main zig dev builds right now, I'll look into what would be needed for cross compilation.

**Comment by JonSnowbd** [comment]
I'm not as invested in cross compilation now, I'll definitely revisit this when zig is a bit more mature, maybe after .11
