### ISSUE TITLE
Changes for zig 0.9.0

### ISSUE THREAD

**Issue by realgdman** [JonSnowbd/ZT#13]
Hello, I'm new to zig and experimented with this useful library, I don't have PR but here's what I have found to be changed:
1. Allocator now is object itself, not pointer
1.1. Replace declarations `allocator: *Allocator` with `allocator: Allocator`
1.2. Replace usage `&allocator.allocator` with `allocator.allocator()`
2. Custom allocator API changed, `allocFn` is now not field, but argument of `init()`. I'm just using GPA temporarily instead of ringbuffer.
3. `c_void` changed to `anyopaque`. Not sure, may be it need to be `*allowzero anyopaque`
4. Some deprecated `std.debug.warn` changed to `std.debug.print`
5. `std.mem.spanZ(dir_path_ptr)` is now `std.mem.sliceTo(dir_path_ptr, 0)`

**Comment by JonSnowbd** [comment]
Updated everything to 0.10 dev, thank you, and sorry for the long wait. Github for some reason has not sent me emails to notify of issues.
