### ISSUE TITLE
Allow setting data to non-default value

### ISSUE THREAD

**Issue by WesleyAC** [JonSnowbd/ZT#17]
I want to set data to a value that I can only construct at runtime. From peeking at the code, it doesn't seem like this is possible? It would be a nice feature to have.

**Comment by JonSnowbd** [comment]
This is possible by setting the default value to the uninitializable fields to `undefined`, then after .begin you can set it as you like.

**Comment by WesleyAC** [comment]
Ah, that works, thanks! I'm pretty new to zig, so I'm not familiar with these sorts of conventions :)
