### ISSUE TITLE
zt.custom_components.text leads to double-escaping / format string vulns

### ISSUE THREAD

**Issue by WesleyAC** [JonSnowbd/ZT#19]
Dear Imgui users printf-style format strings by default. `zt.custom_components.text` and friends are unaware of this, which makes for a bad time (see attached gif) if you happen to have a `%` character in the text you're trying to print. AFACIT there isn't actually a way, when going through `custom_components.text` to use the builtin string formatting.

I think the ideal solution here is to disable the printf formatting in imgui, but I'm not sure how to do that — haven't really looked at it yet.

![zt_imgui_format_strings](https://user-images.githubusercontent.com/5001092/159592485-0660cecb-7ca2-4c54-ac11-c7a289958863.gif)

**Comment by JonSnowbd** [comment]
For now a potential workaround would be to use `%%` as printf escape. I'll look into handling this in zt's layer.

**Comment by WesleyAC** [comment]
A simple fix is to change:

```zig
ig.igTextWrapped(textFormatted.ptr);
```

to

```zig
ig.igTextWrapped("%s", textFormatted.ptr);
```

Since I'm loading values dynamically, that's what I'm doing for the moment, and it might be a good solution in general.

**Comment by JonSnowbd** [comment]
Looks good, I'll change it up thank you.
