### ISSUE TITLE
Update stb_image version to 2.27

### ISSUE THREAD

**Issue by WesleyAC** [JonSnowbd/ZT#21]
stb_image 2.27 was released ~9 months ago, and contains some fixes that are important to me (at least one crash on a valid jpeg file). Could you update to it?

I would do this myself, but it's not totally clear how to generate `src/pkg/stb_image.zig` — it would be great if you could document that process as well, so that it's more clear how to update it.

Thanks!

**Comment by JonSnowbd** [comment]
Updated to the latest STB. The process is definitely a point of pain, it involves `zig translate-c -lc ./stb_image.h > stb_image.zig` to generate the bindings, then hand editing it down to whats necessary.
