### ISSUE TITLE
Linux build: X11 and GL libs lowercase?

### ISSUE THREAD

**Issue by renerocksai** [JonSnowbd/ZT#22]
Hi there,

Linking with libX11 and libGL on Linux is usually done with `-lX11 -lGL`. However, in `build.zig` lowercase versions of
the library names are used, leading to the flags `-lx11 -lgx` - which doesn't work (on my system, NixOS).

When I changed the two to "GL" and "X11" respectively, the Linux build succeeded.

Am I the only one with this problem?

```zig
// ...

// OpenGL
pub fn glLibrary(exe: *std.build.LibExeObjStep) *std.build.LibExeObjStep {
    // ...
    if (target.isLinux()) {
        gl.linkSystemLibrary("gl");   // channge this to "GL"
    }

// ... and

// GLFW
pub fn glfwLibrary(exe: *std.build.LibExeObjStep) *std.build.LibExeObjStep {
    // ...
    if (target.isLinux()) {
    // ...
        glfw.linkSystemLibrary("x11");    // change this to "X11"
// ...
```

**Comment by JonSnowbd** [comment]
Strangely enough this compiles on ubuntu(the only linux I plan to support) last I tested it, if you can find a more specific platform to use inside of the linux branch that fits NixOS I'll gladly add support for it.
