### ISSUE TITLE
Function for finding system font

### ISSUE THREAD

**Issue by LordMZTE** [JonSnowbd/ZT#23]
It seems like the user of ZT currently always has to provide their own font or write their own code to find a system font. I think it would be a great idea to bundle a function that looks for a system font with ZT to streamline the process of writing applications a little.

**Comment by JonSnowbd** [comment]
This would not be consistent as you would need to depend on the user base all having the requested fonts which vary a lot per os if you're looking for a system font, and require packaging anyway if it's a custom font. 

I'll look into how easy it would be to add a fall back array for this, or if it would be easier to download straight from Google fonts.

**Comment by locriacyber** [comment]
Should be easy on Linux. I think one of Ubuntu X, Noto X, Liberation X should be available.

How to find fonts: `fc-list | cut -f1 -d: | grep -i Liberation`
