### ISSUE TITLE
Allow integer uniforms in genbuffers

### ISSUE THREAD

**Issue by zacwood9** [JonSnowbd/ZT#4]
First of all, thank you so much for this amazing library! It's been a joy to use :)

I was trying to upload a texture uniform and found that integer types were not supported by the generic `setUniform` function.

**Comment by JonSnowbd** [comment]
Thanks for checking out ZT! Caught me before I head to bed, pushed more uniforms in with the breaking changes I had planned today, it won't be too much trouble to update.

You'll just have to remove the path to zt's folder in your build.zig function calls to `link`. so `link("path", b, exe, target)` becomes `link(b, exe, target)`

Let me know if you run into any more issues, I'll check them out in the morning.

**Comment by zacwood9** [comment]
Thanks! Looks like it's working on the dev branch. I'll leave this open until it gets merged to main.
